teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    enable_button: -1
    enable_turbo_button: -1

    #AXES
    axis_linear.x: 1
    axis_linear.y: 0
    axis_angular.yaw: 4


    #SCALE
    scale_linear.x: 1.0
    scale_linear.y: 1.0
    scale_angular.yaw: 1.0

    #TURBO
    scale_linear_turbo.x: 1.0
    scale_linear_turbo.y: 1.0
    scale_angular_turbo.yaw: 1.0
